- id: doi:10.3389/fimmu.2021.636720
  image: https://www.frontiersin.org/files/Articles/636720/fimmu-12-636720-HTML/image_m/fimmu-12-636720-g001.jpg

- id: doi:10.1186/s12979-020-00183-z
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs12979-020-00183-z/MediaObjects/12979_2020_183_Fig1_HTML.png?as=webp

- id: doi:10.1093/bioinformatics/btaa128
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7267827/bin/btaa128f1.jpg

- id: doi:10.1038/s41590-020-0643-3
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41590-020-0643-3/MediaObjects/41590_2020_643_Fig1_HTML.png?as=webp

- id: doi:10.1038/s41467-020-14396-9
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-020-14396-9/MediaObjects/41467_2020_14396_Fig1_HTML.png?as=webp

# BIFET
- id: 10.1093/nar/gky1117
  image : https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/nar/47/2/10.1093_nar_gky1117/1/gky1117fig1.jpeg?Expires=1676662139&Signature=2U9kfdxlMR6sFgfPwSzHKuy1mcTyzZkjjKP0~JkfjDs7ANxs502mUVsm61NlXF4rJdnXexUNbXtUmd15uJteXxjeVSLLHnEbTzySsrVkjXLuzDilkgMt~hD6auP1HgQqAfB5dM6bZ4-fdJduGdBwYGTRkHJOVOQDDNV78jsdW1zl1X8GH0sNdWBoU~rYbs-YrU7TMeJyCxBtepmUW1yZWnoTbdnwu3eSVa-VAn1BdKp50BwiRpvE8Ea5ZkU9TxsCuyo4lSEGVJUYnaMknGVnE89FsSCr7EgxYYfCdTVUfUgyHtJRL-Zr2tNyRk-PMbfnqXOuwua~bbF9uFs06l91aQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1016/j.celrep.2018.12.083
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2211124718320436-fx1.jpg

- id: doi:10.1038/s41598-018-35365-9
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41598-018-35365-9/MediaObjects/41598_2018_35365_Fig1_HTML.png?as=webp

- id: doi:10.1038/s41598-018-34420-9
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41598-018-34420-9/MediaObjects/41598_2018_34420_Fig1_HTML.png?as=webp

# Type 2 Diabetes–Associated Genetic Variants Regulate Chromatin Accessibility in Human Islets 
- id: doi:10.2337/db18-0393
  image: https://ada.silverchair-cdn.com/ada/content_public/journal/diabetes/67/11/10.2337_db18-0393/2/m_db180393f1.jpeg?Expires=1674572482&Signature=B9-rDG3IpJyfE4BaPrCAshsZmUFHsvAf5G7oTBaAki6nXJDPIqXXvxuK-ZET3h4G-q2cObRdTbZAl6-tap3hmF2cylNOF51Bi0yZRxpFmkEeTiBeARuAWYDeXZMwL15zDu2gYRwlQ4r4oo8lGIQOcVpgeWt~t9OuWUrOYb43cq0g9Nqe4dzVcLmeL13r~Cd-7cIr1PvPDGUCZKe7xWI-d6iVQDL62CvHirnhyAwSafcvsNvvtC6znHCZfPoijTrSz9As~ndabTpHD6KLlTycXa55Tq8b45WUl4C6wtxDNxhuep97PAFdmIWUDp5JJlz96rEcoXCc-1i37QuLf5kTQQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

# A Common Type 2 Diabetes Risk Variant Potentiates Activity of an Evolutionarily Conserved Islet Stretch Enhancer and Increases C2CD4A and C2CD4B Expression
- id: doi:10.1016/j.ajhg.2018.02.020
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0002929718300880-gr1.jpg

# I-ATAC: interactive pipeline for the management and pre-processing of ATAC-seq samples. PeerJ 2018.
- id: doi:10.7717/peerj.4040
  image: https://dfzljdn9uc3pi.cloudfront.net/2017/4040/1/fig-1-2x.jpg

# Aging epigenetics: changes and challenges. Book chapter in Epigenetics of Aging and Longevity, Elsevier. 2018
- id: doi:10.1016/B978-0-12-811060-7.00001-2
  image: 

# Chromatin interaction networks revealed unique connectivity patterns of broad H3K4me3 domains and super enhancers in 3D chromatin. Scientific Reports. 2017.
- id: DOI:10.1038/s41598-017-14389-7
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41598-017-14389-7/MediaObjects/41598_2017_14389_Fig1_HTML.jpg?as=webp

# Alpha TC1 and Beta-TC-6 genomic profiling uncovers both shared and distinct transcriptional regulatory features with their primary islet counterparts. Scientific Reports. 2017.
- id: DOI:10.1038/s41598-017-12335-1
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41598-017-12335-1/MediaObjects/41598_2017_12335_Fig1_HTML.jpg?as=webp

# The chromatin accessibility signature of human immune aging stems from CD8+ T cells
- id: 10.1084/jem.20170416
  image: https://cdn.rupress.org/rup/content_public/journal/jem/214/10/10.1084_jem.20170416/4/m_jem_20170416_fig1.jpeg?Expires=1675242187&Signature=wDmcozl6d-Vsqkj8SKFDwlAz-GS8QfBcFrHmg5n--GWifH13NhjLP8MfhmDy-~8XOZnK5MNS1SVOCXsl-KFobfJ8YIJpXNCQxylhQqTPTJh8ypoQNtlYGAgQyPjlOBDoPlaqA3-DOxHgQS6SlQM-ov-rQcPFWBvwOE3Nreqp4aXLkiwS7zYdeYn8qGpgsXuWsCY7-aUAgVo2tUE3iillwD006psDggj7CBXRp2i4poOwNUrzpQQJH1iOSA5PK-hnYfQLUz6X1QWiziNOsxmjXj62lEXmXT87WLEOBwDWdUmDDvwV5G9Q3UgYssWDyE1PiCx2mvZxNB7fqMm37d5l3Q__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

# Genomics of Islet (Dys)function and Type 2 Diabetes. Trends in Genetics. 2017.
- id: 10.1016/j.tig.2017.01.010
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0168952517300215-gr1.jpg

# Computational inference of a genomic pluripotency signature in human and mouse stem cells. Biology Direct, 2016.
- id: DOI:10.1186/s13062-016-0148-z
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs13062-016-0148-z/MediaObjects/13062_2016_148_Fig1_HTML.gif?as=webp

# Leukaemia cell of origin identified by chromatin landscape of bulk tumour cells
- id:  DOI:10.1038/ncomms12166
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fncomms12166/MediaObjects/41467_2016_Article_BFncomms12166_Fig1_HTML.jpg?as=webp

# QuIN: A Web Server for Querying and Visualizing Chromatin Interaction Networks
- id: doi:10.1371/journal.pcbi.1004809
  image: https://storage.googleapis.com/plos-corpus-prod/10.1371/journal.pcbi.1004809/1/pcbi.1004809.g002.PNG_L?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=wombat-sa%40plos-prod.iam.gserviceaccount.com%2F20230113%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230113T202608Z&X-Goog-Expires=86400&X-Goog-SignedHeaders=host&X-Goog-Signature=66fb2af5e91235b414225f1b443d405b365315759941d10fb9c3a5a5db31885bb88790283265d53688b3588fe97ee5c004df27be93e892f32d9dc916fc9654ae43919376269cfbf78981e904cb0fc71a9b631cc838cca42a2384616107d0f5ef9568e030884a7eefdbc2bea01e104fa67b76a38543a4febba2a7a8ddafc76d724ea022d13ac0b6c5750ef677b83d387a2dce4ea80460769f29f2997cb29668bf1f98f0fdc8e47b49dc07ca036d65c3c1b8006993d2b1349bb771400dab718c107b4009190ead57bcaa41cf1d4dd6d3209c84e8fcc9ad27d10d3ebdc30632670d3ea840ca3a43161d7e540535d436b6256dc715a73d20b6b6cd8b0e721bbbaf56

# The tandem duplicator phenotype as a distinct genomic configuration in cancer
- id: doi:10.1073/pnas.1520010113
  image: https://www.pnas.org/cms/10.1073/pnas.1520010113/asset/e29ae6ac-b730-4d22-bcdf-1a7296def06c/assets/graphic/pnas.1520010113fig01.jpeg

# Computational inference of H3K4me3 and H3K27ac domain length
- id: DOI:10.7717/peerj.1750
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/4793332/bin/peerj-04-1750-g001.jpg

# Transcriptional Regulation of the Pancreatic Islet: Implications for Islet Function
- id: doi:10.1007/s11892-015-0635-0
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/4593392/bin/nihms-720991-f0001.jpg

# Cell-specific gene promoters are marked by broader spans of H3K4me3 and are associated with robust gene expression patterns
# No image I guess
- id: doi:10.2217/epi.14.87
  image: 

# Broad H3K4me3 domains promote transcriptional stability at key cell identity and function genes. Cell. 2014. OR NAMED as:
# H3K4me3 Breadth Is Linked to Cell Identity and Transcriptional Consistency
- id: doi:10.1016/j.cell.2014.06.027
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0092867414008174-fx1.jpg

# FOXO3 Shares Common Targets with ASCL1 Genome-wide and Inhibits ASCL1-Dependent Neurogenesis
- id: doi:10.1016/j.celrep.2013.06.035
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2211124713003276-fx1.jpg

# Expansion of oligodendrocyte progenitor cells following SIRT1 inactivation in the adult brain
- id: DOI:10.1038/ncb2735
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fncb2735/MediaObjects/41556_2013_Article_BFncb2735_Fig1_HTML.jpg?as=webp

# Discover regulatory DNA elements using chromatin signatures and artificial neural network
- id: doi:10.1093/bioinformatics/btq248
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bioinformatics/26/13/10.1093_bioinformatics_btq248/1/btq248f1.jpeg?Expires=1676666404&Signature=pb7Ip3i90l-4qgllGnRlIW~n-8UMVkIT7C1ZQp0lXRoBt0p6U6eo7LvyeDISPIjtmDBs8zJLYYWMRIGQoCx5UpjVUO8gE0PypZ2Evzl86UUz3cF6k~p3xJ6O6LOTtRZun6Gga8~n4vc~3pjGOo01g3OqPdbj~lrdWSRCTQIYIvqKzZcRu7Bl64F~jHU7MMlXbxfuNKwVYekCwK73J2V7T25-6ntb-5gOcnXtlbLX5nSnq7r5tn9nQmzmlpUPW4oRDqW~P4HNp79k7WpwtP3kkxjPnfz-vHB1BE6E4Kaul8wFp9jn9XjlS7p69sduja0Kz~m5wuVV9IU8-2gGBuPeiw__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

# Combinatorial chromatin modification patterns in the human genome revealed by subspace clustering
- id: doi:10.1093/nar/gkr016
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/3105409/bin/gkr016f1.jpg

#  Predicting functionality of protein–DNA interactions by integrating diverse evidence 
- id: DOI:10.1093/bioinformatics/btp213 
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/2687967/bin/btp213f1.jpg

# Construction of a reference gene association network from multiple profiling data: application to data analysis
- id: doi:10.1093/bioinformatics/btm423
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bioinformatics/23/20/10.1093_bioinformatics_btm423/2/m_btm423f1.jpeg?Expires=1676666515&Signature=W5YsTgtEoVTCgN0YADSk2Qy~wrcxJZzB8wnv6e3hwyrHTmePzNKPW~pRYoBz-QMpZ7oPNXSaX1-f7jIx95ebzEA19THMzyYmvEp8lDtbwHVe82UXv8kSPtHk3mONErAf7MutfglUVuJU5fyUZRi7q047uPNYZRgcv0vGmVG5CtTJ3if91ujAxJKc6IGQfneA4RV5VmbPiZ2Wb2OnoMRu6JrDvip752s3aPSzZqCO9bjC6B0beJlNIKf7biebJL9zxiXUeoQDgyeYMmarTC0VG4UI8TjQHcoCH6yfMIkp1p7H5HmTtWYlKIJESMcWL53ovinmnExdOulvL3n5yFhnKg__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

  

# - id: doi:10.1016/j.csbj.2020.05.017
#   image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg
#   date: 2020-6-2
#   extra-links:
#     - type: manubot
#       link: https://greenelab.github.io/knowledge-graph-review/
#   tags:
#     - knowledge graphs

# - id: doi:10.1371/journal.pcbi.1007128
#   image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#   repo: greenelab/meta-review
#   extra-links:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/

# - id: doi:10.7554/eLife.32822
#   image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
#   extra-links:
#     - type: preprint
#       link: https://doi.org/10.7287/peerj.preprints.3100v1
#     - type: manubot
#       link: https://greenelab.github.io/scihub-manuscript/
#     - type: source
#       link: https://github.com/greenelab/scihub-manuscript
#       text: Manuscript source
#     - type: source
#       link: https://github.com/greenelab/scihub
#       text: Analyses source
